FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update
RUN apt-get -qq install -y python python-dev python-virtualenv python3-virtualenv python3-dev build-essential perl wget postgresql postgresql-client libpq-dev libssl-dev libz-dev libffi-dev sqlite3 libjpeg-dev libxslt1-dev git locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN wget -q https://github.com/matrix-org/sytest/raw/develop/install-deps.pl
RUN wget -q https://github.com/matrix-org/sytest/raw/develop/cpanfile
RUN perl install-deps.pl

RUN mkdir /test
RUN mkdir /src
RUN mkdir /logs
WORKDIR /test

ADD docker_sytest.sh /docker_sytest.sh
ENTRYPOINT /docker_sytest.sh
