pip install --upgrade --force jsonschema
pip install --upgrade --force frozendict
pip install --upgrade --force unpaddedbase64
pip install --upgrade --force canonicaljson
pip install --upgrade --force signedjson
pip install --upgrade --force pynacl
pip install --upgrade --force service_identity
pip install --upgrade --force Twisted
pip install --upgrade --force treq
pip install --upgrade --force pyopenssl
pip install --upgrade --force pyyaml
pip install --upgrade --force pyasn1
pip install --upgrade --force pyasn1-modules
pip install --upgrade --force daemonize
pip install --upgrade --force bcrypt
pip install --upgrade --force pillow
pip install --upgrade --force pydenticon
pip install --upgrade --force sortedcontainers
pip install --upgrade --force psutil
pip install --upgrade --force pysaml2
pip install --upgrade --force pymacaroons-pynacl
pip install --upgrade --force msgpack-python
pip install --upgrade --force phonenumbers
pip install --upgrade --force six
pip install --upgrade --force prometheus_client
pip install --upgrade --force attrs
pip install --upgrade --force netaddr
