#!/bin/bash

SYNAPSE="synapse/app/homeserver.py"

CONFIGFILE="homeserver.yaml"
PIDFILE="homeserver.pid"

GREEN=$'\e[1;32m'
NORMAL=$'\e[m'

set -e

case "$1" in
  start)
    if [ ! -f "$CONFIGFILE" ]; then
      echo "No config file found"
      echo "To generate a config file, run 'python --generate-config'"
      exit 1
    fi

    echo -n "Starting ..."
    $SYNAPSE --daemonize -c "$CONFIGFILE" --pid-file "$PIDFILE"
    echo "${GREEN}started${NORMAL}"
    ;;
  stop)
    echo -n "Stopping ..."
    test -f $PIDFILE && kill `cat $PIDFILE` && echo "${GREEN}stopped${NORMAL}"
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 [start|stop|restart]" >&2
    exit 1
esac
