{
 "title": "Synapse",
 "tags": [ "matrix" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "bucket_size", "label": "Bucket Size", "query": "30s,1m,2m,5m,10m,15m" },
   {
    "name": "instance",
    "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, instance)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, job)"
   },
   {
    "name": "index",
    "query": "label_values(synapse_util_metrics_block_ru_utime_seconds, index)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Send Time (excluding errors, all workers)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Event Send Time Quantiles (excluding errors, all workers)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.05, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) by (le))",
     "legendFormat": "5%"
    },
    {
     "expr": "sum(rate(synapse_http_server_response_time_seconds_sum{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size])) / sum(rate(synapse_http_server_response_time_seconds_count{servlet='RoomSendEventRestServlet',index=~\"$index\",instance=\"$instance\",code=~\"2..\"}[$bucket_size]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(rate(synapse_storage_events_persisted_events{instance=\"$instance\"}[$bucket_size]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
     "legendFormat": "{{job}}-{{index}} "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
     "legendFormat": "{{job}} {{index}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
     "legendFormat": "{{job}}-{{index}}"
    }
   ]
  },
  {
   "title": "Process info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_system_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} system "
      },
      {
       "expr": "rate(process_cpu_user_seconds_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} user"
      }
     ]
    },
    {
     "title": "Reactor tick quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of reactor ticks completed, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(python_twisted_reactor_tick_time_bucket{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} 90%"
      },
      {
       "expr": "rate(python_twisted_reactor_tick_time_sum{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size]) / rate(python_twisted_reactor_tick_time_count{index=~\"$index\",instance=\"$instance\",job=~\"$job\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} mean"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}} {{index}}"
      },
      {
       "expr": "sum(process_resident_memory_bytes{instance=\"$instance\",job=~\"$job\",index=~\"$index\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Prometheus scrape time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Up",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(up{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Stacked CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_response_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_response_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      },
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_client_requests{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}}"
      },
      {
       "expr": "rate(synapse_http_matrixfederationclient_requests{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} (federation)"
      }
     ]
    }
   ]
  },
  {
   "title": "Event persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Send Time (Including errors, across all workers)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\"}[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events Persisted (all workers)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events{instance=\"$instance\"}[$bucket_size])) without (job,index)"
      }
     ]
    },
    {
     "title": "Events/s Local vs Remote",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_source_type{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_event_type{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_events_persisted_by_origin{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Memberships/s by Origin",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_persisted_events_sep{job=~\"$job\",index=~\"$index\", type=\"m.room.member\",instance=\"$instance\", origin_type=\"local\"}[$bucket_size])) by (origin_type, origin_entity)",
       "legendFormat": "{{origin_entity}} ({{origin_type}})"
      }
     ]
    },
    {
     "title": "Event send time quantiles by worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(synapse_http_server_response_time_seconds_bucket{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method))",
       "legendFormat": "{{job}}-{{index}} 50%"
      },
      {
       "expr": "sum(rate(synapse_http_server_response_time_seconds_sum{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method) / sum(rate(synapse_http_server_response_time_seconds_count{servlet='RoomSendEventRestServlet',instance=\"$instance\",code=~\"2..\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (method)",
       "legendFormat": "{{job}}-{{index}} mean"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count by arrival time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Top 10 Request Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",index=~\"$index\",method!=\"OPTIONS\"}[$bucket_size]) and topk(10,synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",method!=\"OPTIONS\"})",
       "legendFormat": "{{method}} {{servlet}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Total CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_in_flight_requests_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_in_flight_requests_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage by Endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_http_server_in_flight_requests_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_http_server_in_flight_requests_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) / rate(synapse_http_server_requests_received{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "DB Usage by endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_server_in_flight_requests_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}} {{tag}}"
      }
     ]
    },
    {
     "title": "Non-sync avg response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(synapse_http_server_response_time_seconds_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])) without (code))/(sum(rate(synapse_http_server_response_time_seconds_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\",tag!=\"incremental_sync\"}[$bucket_size])) without (code))",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}}"
      }
     ]
    },
    {
     "title": "Requests in flight",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,synapse_http_server_in_flight_requests_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"})",
       "legendFormat": "{{job}}-{{index}} {{method}} {{servlet}}"
      },
      {
       "expr": "sum(avg_over_time(synapse_http_server_in_flight_requests_count{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Background jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by background jobs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])+rate(synapse_background_process_ru_stime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "DB usage by background jobs (including scheduling time)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_background_process_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) +  rate(synapse_background_process_db_sched_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Background jobs in flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_background_process_in_flight_count{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing federation transaction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_client_sent_transactions{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "successful txn rate"
      },
      {
       "expr": "sum(rate(synapse_util_metrics_block_count{block_name=\"_send_new_transaction\",instance=\"$instance\"}[$bucket_size]) - ignoring (block_name) rate(synapse_federation_client_sent_transactions{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "failed txn rate"
      }
     ]
    },
    {
     "title": "Incoming PDU/EDU rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_server_received_pdus{instance=~\"$instance\"}[$bucket_size]))",
       "legendFormat": "pdus"
      },
      {
       "expr": "sum(rate(synapse_federation_server_received_edus{instance=~\"$instance\"}[$bucket_size]))",
       "legendFormat": "edus"
      }
     ]
    },
    {
     "title": "Outgoing PDU/EDU rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_client_sent_pdu_destinations:total{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "pdus"
      },
      {
       "expr": "sum(rate(synapse_federation_client_sent_edus{instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "edus"
      }
     ]
    },
    {
     "title": "Outgoing EDUs by type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_federation_client_sent_edus_by_type{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "In-memory federation transmission queues",
     "type": "graph",
     "description": "The number of events in the in-memory queues ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_transaction_queue_pending_pdus{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "pending PDUs {{job}}-{{index}}"
      },
      {
       "expr": "synapse_federation_transaction_queue_pending_edus{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "pending EDUs {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Outgoing EDU queues on master",
     "type": "graph",
     "description": "Number of events queued up on the master process for processing by the federation sender",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "synapse_federation_send_queue_presence_changed_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence changed"
      },
      {
       "expr": "synapse_federation_send_queue_presence_map_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence map"
      },
      {
       "expr": "synapse_federation_send_queue_presence_destinations_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "presence destinations"
      },
      {
       "expr": "synapse_federation_send_queue_keyed_edu_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "keyed edus"
      },
      {
       "expr": "synapse_federation_send_queue_edus_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "other edus"
      },
      {
       "expr": "synapse_federation_send_queue_pos_time_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "stream positions"
      }
     ]
    },
    {
     "title": "Federation send PDU lag",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(rate(synapse_event_processing_lag_by_event_bucket{instance=\"$instance\",name=\"federation_sender\"}[$bucket_size])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Federation send PDU lag quantiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "25%"
      },
      {
       "expr": "histogram_quantile(0.05, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) by (le))",
       "legendFormat": "5%"
      },
      {
       "expr": "sum(rate(synapse_event_processing_lag_by_event_sum{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size])) / sum(rate(synapse_event_processing_lag_by_event_count{name='federation_sender',index=~\"$index\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Handle inbound PDU time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(rate(synapse_federation_server_pdu_process_time_bucket{instance=\"$instance\"}[$bucket_size])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pushes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Push rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_http_httppusher_http_pushes_processed{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) and on (instance, job, index) (synapse_http_httppusher_http_pushes_failed + synapse_http_httppusher_http_pushes_processed) > 0",
       "legendFormat": "processed {{job}}"
      },
      {
       "expr": "rate(synapse_http_httppusher_http_pushes_failed{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) and on (instance, job, index) (synapse_http_httppusher_http_pushes_failed + synapse_http_httppusher_http_pushes_processed) > 0",
       "legendFormat": "failed {{job}}"
      }
     ]
    },
    {
     "title": "Active pusher instances by app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,synapse_pushers{job=~\"$job\",index=~\"$index\", instance=\"$instance\"})",
       "legendFormat": "{{kind}} {{app_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg time waiting for db conn",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Db scheduling time quantiles",
     "type": "graph",
     "description": "Shows the time in which the given percentage of database queries were scheduled, over the sampled timespan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 95%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_schedule_time_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}} {{index}} 90%"
      },
      {
       "expr": "rate(synapse_storage_schedule_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_schedule_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}} {{index}} mean"
      }
     ]
    },
    {
     "title": "Top DB transactions by txn rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_storage_transaction_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "DB transactions by total txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    },
    {
     "title": "Average DB txn time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_storage_transaction_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(synapse_storage_transaction_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{desc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-block metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\",block_name!=\"wrapped_request_handler\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average CPU Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(rate(synapse_util_metrics_block_ru_utime_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) + rate(synapse_util_metrics_block_ru_stime_seconds[$bucket_size])) / rate(synapse_util_metrics_block_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Total DB Usage by Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Database Transaction time, by Block",
     "type": "graph",
     "description": "The time each database transaction takes to execute, on average, broken down by metrics block.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Transactions per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_db_txn_duration_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_db_txn_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Average Wallclock Time per Block",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_time_seconds{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]) / rate(synapse_util_metrics_block_count[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    },
    {
     "title": "Block count",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_metrics_block_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{block_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:hits{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])/rate(synapse_util_caches_cache:total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_util_caches_cache:size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache request rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:total{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Top 10 cache misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(synapse_util_caches_cache:total{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size]) - rate(synapse_util_caches_cache:hits{job=\"$job\",instance=\"$instance\"}[$bucket_size]))",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Cache eviction rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "hertz", "label": "entries / second" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_cache:evicted_size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_util_caches_response_cache:size{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Response cache hit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_util_caches_response_cache:hits{instance=\"$instance\", job=~\"$job\", index=~\"$index\"}[$bucket_size])/rate(synapse_util_caches_response_cache:total{instance=\"$instance\", job=~\"$job\", index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{name}} {{job}}-{{index}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total GC time by bucket (10m smoothing)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[10m])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Average GC Time Per Collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_sum{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_gc_time_count[$bucket_size])",
       "legendFormat": "{{job}} {{index}} gen {{gen}} "
      }
     ]
    },
    {
     "title": "Allocation counts",
     "type": "graph",
     "description": "'gen 0' shows the number of objects allocated since the last gen0 GC.\n'gen 1' / 'gen 2' show the number of gen0/gen1 GCs since the last gen1/gen2 GC.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      {
       "format": "short",
       "label": "Gen N-1 GCs since last Gen N GC"
      }
     ],
     "targets": [
      {
       "expr": "python_gc_counts{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "Object counts per collection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_unreachable_total{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(python_gc_time_count{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} gen {{gen}}"
      }
     ]
    },
    {
     "title": "GC durations",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "sum(rate(python_gc_time_bucket[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of incoming commands",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_inbound_commands{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    },
    {
     "title": "Queued incoming RDATA commands, by stream",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_replication_tcp_command_queue{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{stream_name}} {{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Rate of outgoing commands",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum (rate(synapse_replication_tcp_protocol_outbound_commands{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])) without (name, conn_id)",
       "legendFormat": "{{job}}-{{index}} {{command}}"
      }
     ]
    },
    {
     "title": "Outgoing stream updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_resource_stream_updates{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{stream_name}}"
      }
     ]
    },
    {
     "title": "Replication connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_replication_tcp_resource_connections_per_stream{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}} {{stream_name}}"
      },
      {
       "expr": "synapse_replication_tcp_resource_total_connections{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}",
       "legendFormat": "{{job}}-{{index}}"
      }
     ]
    },
    {
     "title": "Replication connection close reasons",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_replication_tcp_protocol_close_reason{job=~\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{job}}-{{index}} {{reason_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event processing loop positions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event processing lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": "max(synapse_event_persisted_position{instance=\"$instance\"}) - on() group_right() synapse_event_processing_positions{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Age of last processed event",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "time()*1000-synapse_event_processing_last_ts{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    },
    {
     "title": "Event processing catchup rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      {
       "format": "none",
       "label": "fallbehind(-) / catchup(+):  s/sec"
      }
     ],
     "targets": [
      {
       "expr": "deriv(synapse_event_processing_last_ts{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])/1000 - 1",
       "legendFormat": "{{job}}-{{index}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extremities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of rooms, by number of forward extremities in room",
     "type": "heatmap",
     "description": "Colour reflects the number of rooms with the given number of forward extremities, or fewer.\n\nThis is only updated once an hour.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "synapse_forward_extremities_bucket{instance=\"$instance\"} and on (index, instance, job) (synapse_storage_events_persisted_events > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Room counts, by number of extremities",
     "type": "graph",
     "description": "Number of rooms with the given number of forward extremities or fewer.\n\nThis is only updated once an hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "Number of rooms" }
     ],
     "targets": [
      {
       "expr": "synapse_forward_extremities_bucket{instance=\"$instance\"} > 0",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of forward extremities in room (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of events persisted to rooms with the given number of forward extremities, or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of forward extremities in room (quantiles)",
     "type": "graph",
     "description": "For a given percentage P, the number X where P% of events were persisted to rooms with X forward extremities or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Number of extremities in room" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_events_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Events persisted, by number of stale forward extremities in room (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of events persisted to rooms with the given number of stale forward extremities, or fewer.\n\nStale forward extremities are those that were in the previous set of extremities as well as the new.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Events persisted, by number of stale forward extremities in room (quantiles)",
     "type": "graph",
     "description": "For  given percentage P, the number X where P% of events were persisted to rooms with X stale forward extremities or fewer.\n\nStale forward extremities are those that were in the previous set of extremities as well as the new.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      {
       "format": "short",
       "label": "Number of stale forward extremities in room"
      }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_storage_events_stale_forward_extremities_persisted_bucket{instance=\"$instance\"}[$bucket_size]) and on (index, instance, job) (synapse_storage_events_persisted_events > 0))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Number of state resolution performed, by number of state groups involved (heatmap)",
     "type": "heatmap",
     "description": "Colour reflects the number of state resolution operations performed over the given number of state groups, or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of state resolutions performed, by number of state groups involved (quantiles)",
     "type": "graph",
     "description": "For a given percentage P, the number X where P% of state resolution operations took place over X state groups or fewer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short", "label": "Number of state groups" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.75, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.90, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.99, rate(synapse_state_number_state_groups_in_resolution_bucket{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Stale extremity dropping",
     "type": "graph",
     "description": "When we do a state res while persisting events we try and see if we can prune any stale extremities.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "sum(rate(synapse_storage_events_state_resolutions_during_persistence{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "State res "
      },
      {
       "expr": "sum(rate(synapse_storage_events_potential_times_prune_extremities{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "Potential to prune"
      },
      {
       "expr": "sum(rate(synapse_storage_events_times_pruned_extremities{instance=\"$instance\",job=~\"$job\",index=~\"$index\"}[$bucket_size]))",
       "legendFormat": "Pruned"
      }
     ]
    }
   ]
  },
  {
   "title": "MAU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "MAU Limits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_admin_mau:current{instance=\"$instance\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "synapse_admin_mau:max{instance=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "MAU by Appservice",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "synapse_admin_mau_current_mau_by_service{instance=\"$instance\"}",
       "legendFormat": "{{ app_service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Notifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifier Streams Woken",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_notifier_users_woken_by_stream{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{stream}} {{index}}"
      }
     ]
    },
    {
     "title": "Presence Stream Fetch Type Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_get_updates{job=~\"$job\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{type}} {{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Appservices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent Events rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_appservice_api_sent_events{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{exported_service}}"
      }
     ]
    },
    {
     "title": "Transactions rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_appservice_api_sent_transactions{instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{exported_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Presence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Presence",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_notified_presence{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Notified"
      },
      {
       "expr": "rate(synapse_handler_presence_federation_presence_out{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Remote ping"
      },
      {
       "expr": "rate(synapse_handler_presence_presence_updates{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Total updates"
      },
      {
       "expr": "rate(synapse_handler_presence_federation_presence{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Remote updates"
      },
      {
       "expr": "rate(synapse_handler_presence_bump_active_time{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "Bump active time"
      }
     ]
    },
    {
     "title": "Presence state transitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_state_transition{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{from}} -> {{to}}"
      }
     ]
    },
    {
     "title": "Presence  notify reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_handler_presence_notify_reason{job=\"$job\",index=~\"$index\",instance=\"$instance\"}[$bucket_size])",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Cache Set Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_external_cache_set{job=\"$job\", instance=\"$instance\", index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{ cache_name }} {{ index }}"
      }
     ]
    },
    {
     "title": "External Cache Get Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "rate(synapse_external_cache_get{job=\"$job\", instance=\"$instance\", index=~\"$index\"}[$bucket_size])",
       "legendFormat": "{{ cache_name }} {{ index }}"
      }
     ]
    },
    {
     "title": "External Cache Response Time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(synapse_external_cache_response_time_seconds_bucket{index=~\"$index\",instance=\"$instance\",job=\"$job\"}[$bucket_size])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}