const state = {
    setupUI: {
        activeBlocks: ["block1"],
    },
    configUI: {

    },
    baseConfig: {
        setupDone: true,
        baseConfigChecked: false,
        servername: "server_name",
        reportStats: false,
        gettingSecretKey: false,
        secretKey: "asdfsadf",
        delegationType: "local|well_known|DNS_SRV",
        delegationServerName: "name",
        delegationFederationPort: "\"\"|325",
        delegationClientPort: "\"\"|325",
        reverseProxy: "nginx|caddy|apache|haproxy|other|none",
        tls: "acme|tls|reverseproxy",
        testingCertPaths: true,
        uploadingCerts: true,
        certPathInvalid: true,
        certKeyPathInvalid: true,
        tlsCertPath: "sadfaf",
        tlsCertKeyPath: "sdfasdf",
        tlsCertFile: "sadfa;dlf;sad;fkla;sdlfjkas;dlfkjas;dflkja;sdfkljadf ------",
        tlsCertKeyFile: "sadfa;dlf;sad;fkla;sdlfjkas;dlfkjas;dflkja;sdfkljadf ------",
        tlsPath: "sdasfaf/a/fdasfd/a/fasd/",
        verifyingPorts: true,
        synapseFederationPortFree: true,
        synapseClientPortFree: true,
        synapseFederationPort: 1234,
        synapseClientPort: 1234,
        database: "sqlite3|postgres",
        configDir: "sadfasdf",
    },
}