ARG distro="debian:stable"
FROM ${distro} AS dpkg-build
RUN apt-get update -qq -o Acquire::Languages=none \
    && env DEBIAN_FRONTEND=noninteractive apt-get install \
        -yqq --no-install-recommends -o Dpkg::Options::=--force-unsafe-io \
        build-essential debhelper devscripts equivs dh-virtualenv libpq-dev sqlite3 python3-dev libffi-dev libjpeg-dev zlib1g-dev libxslt1-dev python3-setuptools python3-pip libssl-dev lsb-release dh-systemd
WORKDIR /synapse/build
ENTRYPOINT ["bash","/synapse/build/debian/build_debian.sh"]

