#!/bin/bash
#
# A script which checks that an appropriate news file has been added on this
# branch.

set -e

# make sure that origin/develop is up to date
git fetch origin develop

UPSTREAM=origin/develop

# if there are changes in the debian directory, check that the debian changelog
# has been updated
if ! git diff --quiet $UPSTREAM... -- debian; then
    if git diff --quiet $UPSTREAM... -- debian/changelog; then
        echo "Updates to debian directory, but no update to the changelog." >&2
        exit 1
    fi
fi

# if there are changes *outside* the debian directory, check that the
# newsfragments have been updated.
if git diff --name-only $UPSTREAM... | grep -qv '^develop/'; then
    tox -e check-newsfragment
fi

# check that any new newsfiles on this branch end with a full stop.
for f in git diff --name-only $UPSTREAM... -- changelog.d; do
    lastchar=`tr -d '\n' < $f | tail -c 1`
    if [ $lastchar != '.' ]; then
        echo "Newsfragment $f does not end with a '.'" >&2
        exit 1
    fi
done

